version: 2
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
#      docker_layer_caching: true
    steps:
      - checkout
      #- setup_remote_docker:
      #    docker_layer_caching: true
      - restore_cache:
          key: sbt-cache
      - run:
          name: pyenv
          command: pyenv global 3.7.0
      - run:
          name: ls
          command: pwd && ls
      - run:
          name: Install third party dependencies
          command: ./make.py dev_third_party
      - run:
          name: Check source code formatting
          command: ./make.py dev_format_check
      - run:
          name: Execute tests
          command: ./make.py dev_test
      # NOTE: --mount not supported by CircleCI Docker version.
#      - run:
#          name: Build Docker image
#          command: ./make.py docker_build
#      - run:
#          name: Push Docker image
#          command: ./make.py docker_push
      - save_cache:
          key: sbt-cache
          paths:
            - "~/.ivy2/cache"
            - "~/.sbt"
            - "~/.m2"